wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1664700693.319502
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 100
image_size:
  desc: null
  value: 640
learning_rate:
  desc: null
  value: 0.001
